export const TripTimeFormats = {
  FULL_DATE_FORMAT: `DD/MM/YY HH:MM`,
  TIME_FORMAT: `HH:MM`,
  TRIP_INFO_START_DATE_FORMAT: `MMM DD`,
  TRIP_INFO_END_DATE_FORMAT: `DD MMM`,
  TRIP_TIME_FORMAT: `H[H] MM[M]`,
};
